name: Run Notebooks

on:
  push:
    paths:
      - 'notebooks/processing.ipynb'
      - 'notebooks/training.ipynb'
      - 'data/raw/**'
      - '.github/workflows/run-notebooks.yml'

jobs:
  execute-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill


      - name: Create output directory
        run: mkdir -p output

      - name: Run preprocessing notebook
        run: papermill notebooks/processing.ipynb output/processing-executed.ipynb

      - name: Run training notebook
        run: papermill notebooks/training.ipynb output/training-executed.ipynb

      - name: Upload model and encoders
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/model.pkl
            models/transformers/label_encoders.pkl


      - name: Upload executed notebooks
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebooks
          path: output/
